### ISSUE TITLE
deadlocking_for_multiprocess

### ISSUE THREAD

**Issue by ahmad11111111111** [ahmad11111111111/Brain-Controller-App#4]

**Comment by ahmad11111111111** [comment]
trying to get the sub-process to close without a deadlock forming.

**Comment by ahmad11111111111** [comment]
remote: error: File controller/controler_inputs.ipynb is 310.12 MB; this exceeds GitHub's file size limit of 100.00 MB        
remote: error: GH001: Large files detected. You may want to try Git Large File Storage - https://git-lfs.github.com.

**Comment by kevincar** [comment]
Hey @ahmad11111111111 , What is the specific problem associated with this issue so that I can help? The title mentions deadlocking but your comments reference LFS problem?

**Comment by ahmad11111111111** [comment]
I think if fixed the deadlocked problem by adding a delay in the sampling but I can't push my code because the ipynb file is 300MB

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Kevin Davis ***@***.***>
Sent: Monday, September 11, 2023 2:49:07 PM
To: ahmad11111111111/Brain-Controller-App ***@***.***>
Cc: Al-Salem, Ahmad Tarik ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ahmad11111111111/Brain-Controller-App] deadlocking_for_multiprocess (Issue #4)

CAUTION: This email originated from outside the organization. DO NOT CLICK ON LINKS or OPEN ATTACHMENTS unless you know and trust the sender.

Hey @ahmad11111111111<https://github.com/ahmad11111111111> , What is the specific problem associated with this issue so that I can help? The title mentions deadlocking but your comments reference LFS problem?

**Comment by kevincar** [comment]
OK. I just deleted the file.

**Comment by ahmad11111111111** [comment]
Do you have any idea why it's that big?

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Kevin Davis ***@***.***>
Sent: Monday, September 11, 2023 2:53:25 PM
To: ahmad11111111111/Brain-Controller-App ***@***.***>
Cc: Al-Salem, Ahmad Tarik ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ahmad11111111111/Brain-Controller-App] deadlocking_for_multiprocess (Issue #4)

CAUTION: This email originated from outside the organization. DO NOT CLICK ON LINKS or OPEN ATTACHMENTS unless you know and trust the sender.

K. I just deleted the file

**Comment by ahmad11111111111** [comment]
I'll try pushing again. I tried copying and the code into a new ipynd and that didn't work.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by ahmad11111111111** [comment]
still not working

**Comment by ahmad11111111111** [comment]
To https://github.com/ahmad11111111111/Brain-Controller-App.git
 ! [remote rejected] 4-deadlocking_for_multiprocess -> 4-deadlocking_for_multiprocess (pre-receive hook declined)
error: failed to push some refs to

**Comment by kevincar** [comment]
Fixed

**Comment by ahmad11111111111** [comment]
I'm still getting the same error when I try to push

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Kevin Davis ***@***.***>
Sent: Monday, September 11, 2023 3:22:09 PM
To: ahmad11111111111/Brain-Controller-App ***@***.***>
Cc: Al-Salem, Ahmad Tarik ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ahmad11111111111/Brain-Controller-App] deadlocking_for_multiprocess (Issue #4)

CAUTION: This email originated from outside the organization. DO NOT CLICK ON LINKS or OPEN ATTACHMENTS unless you know and trust the sender.

Fixed

**Comment by ahmad11111111111** [comment]
Even after pulling

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by kevincar** [comment]
It's possible your current notebook is the problem. How big is the notebook you're trying to push?

**Comment by ahmad11111111111** [comment]
It's only 2 blocks. The loop that's about the same size that it was and a small test scrip. Should I try and convert those into 2 .py files?

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Kevin Davis ***@***.***>
Sent: Monday, September 11, 2023 3:28:07 PM
To: ahmad11111111111/Brain-Controller-App ***@***.***>
Cc: Al-Salem, Ahmad Tarik ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ahmad11111111111/Brain-Controller-App] deadlocking_for_multiprocess (Issue #4)

CAUTION: This email originated from outside the organization. DO NOT CLICK ON LINKS or OPEN ATTACHMENTS unless you know and trust the sender.

It's possible your current notebook is the problem. How big is the notebook you're trying to push?

**Comment by kevincar** [comment]
It's possible that there is output text that is making the file large. You can try and make a new notebook, copy the cell contents over without running it, delete the old notebook and replace it with the new one and push.

**Comment by ahmad11111111111** [comment]
I did that already and I made sure to clear the output

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Kevin Davis ***@***.***>
Sent: Monday, September 11, 2023 3:39:15 PM
To: ahmad11111111111/Brain-Controller-App ***@***.***>
Cc: Al-Salem, Ahmad Tarik ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ahmad11111111111/Brain-Controller-App] deadlocking_for_multiprocess (Issue #4)

CAUTION: This email originated from outside the organization. DO NOT CLICK ON LINKS or OPEN ATTACHMENTS unless you know and trust the sender.

It's possible that there is output text that is making the file large. You can try and make a new notebook, copy the cell contents over without running it, delete the old notebook and replace it with the new one and push.

**Comment by ahmad11111111111** [comment]
I think it may be saving all of the history. I could try making a new repository.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Kevin Davis ***@***.***>
Sent: Monday, September 11, 2023 3:39:15 PM
To: ahmad11111111111/Brain-Controller-App ***@***.***>
Cc: Al-Salem, Ahmad Tarik ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ahmad11111111111/Brain-Controller-App] deadlocking_for_multiprocess (Issue #4)

CAUTION: This email originated from outside the organization. DO NOT CLICK ON LINKS or OPEN ATTACHMENTS unless you know and trust the sender.

It's possible that there is output text that is making the file large. You can try and make a new notebook, copy the cell contents over without running it, delete the old notebook and replace it with the new one and push.

**Comment by kevincar** [comment]
That's probably overkill. I can push to the repository so it's not the repository causing the issue. It's your local setup. Save your file else where, delete your local repo, reclone, and try again

**Comment by ahmad11111111111** [comment]
Got it

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Kevin Davis ***@***.***>
Sent: Monday, September 11, 2023 3:49:16 PM
To: ahmad11111111111/Brain-Controller-App ***@***.***>
Cc: Al-Salem, Ahmad Tarik ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ahmad11111111111/Brain-Controller-App] deadlocking_for_multiprocess (Issue #4)

CAUTION: This email originated from outside the organization. DO NOT CLICK ON LINKS or OPEN ATTACHMENTS unless you know and trust the sender.

That's probably overkill. I can push to the repository so it's not the repository causing the issue. It's your local setup. Save your file else where, delete your local repo, reclone, and try again

**Comment by kevincar** [comment]
So you were able to push?

**Comment by ahmad11111111111** [comment]
I had to leave for a bit. Will be back in about 2 hours. Sorry.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Kevin Davis ***@***.***>
Sent: Monday, September 11, 2023 3:59:04 PM
To: ahmad11111111111/Brain-Controller-App ***@***.***>
Cc: Al-Salem, Ahmad Tarik ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ahmad11111111111/Brain-Controller-App] deadlocking_for_multiprocess (Issue #4)

CAUTION: This email originated from outside the organization. DO NOT CLICK ON LINKS or OPEN ATTACHMENTS unless you know and trust the sender.

So you were able to push?
